### ISSUE TITLE
Need clarification: how to use

### ISSUE THREAD

**Issue by k-sheth** [jeffbski/joi-full#1]
Hi,

Thanks for making this. Been following the issues, so i know you have been through some trouble for making this.

In joi-browser, the npm package included the dist/joi-browser.js and dist/joi-browser.min.js files, but is not the case in joi-full. Is that intended ?

I have my build setup such that most of my transpiling happens out side of webpack and webpack loaders typically dont transpile files in node_modules. When I run my build with joi-full, and uglify, i see that uglify fails because it finds let / const. the difference between joi-full and joi-browser seems to be the lack of dist folder with the transpiled files.

Thanks for spending so much time with this. Appreciate your help.

Thanks

**Comment by jeffbski** [comment]
@k-sheth thanks for reporting this, it looks like maybe the dist files didn't get published, I think I am missing a .npmignore and possibly it is defaulting to what is in .gitignore. I'll see about correcting this and run some more tests.

**Comment by jeffbski** [comment]
@k-sheth ok, I think I found the issues.

 - missing .npmignore so it defaulted to the .gitignore and thus ignored publishing the dist folder
 - package.json browser field - changed it to the string version for defining the bundled src to use for browsers. Apparently webpack doesn't work with the object version of the browser field so one has to use the string way. (The object version for browser field allows you to specify not only the main but other replacements as well. We only needed main for this, so the string version will work fine).

I have update the examples/webpack-basic build using packageAlias:browser and also I setup some of the babel loader properly so that it would compile to ES5. 

So if you use the newest version joi-full@10.0.6-beta2  and set things up like the webpack-basic example, it should compile things down so it is ES5 (no let or const) and thus uglify should work properly after that.

Let me know how it goes and if everything looks good, we can update this to 10.0.6 

I didn't want to update until it looks good for everyone since npm doesn't allow overwriting a version anymore.

**Comment by k-sheth** [comment]
Will try out and report here in a few hours.

**Comment by k-sheth** [comment]
:) works now.

I would suggest to wait for joi to update to its next version and then publish 10.0.6 so that versions are in sync.

I would also suggest that joi-browser README point to joi-full for anyone wanting to use the newer versions of joi.

thanks for all youe help.

**Comment by jeffbski** [comment]
I found out Joi had just bumped up to 10.0.6 so we can stay in sync with that version now too.

**Comment by jeffbski** [comment]
@k-sheth thanks for checking this out and getting back to me
